export interface Builder {
  id: string;
  name: string;
  image: string;
  networks: string[];
  rewardType: string;
  minDeposit: number;
  totalStaked: number;
  stakingCount: number;
  lockPeriod: string;
}

export const builders: Builder[] = [
  {
    id: "1",
    name: "Venice",
    image: "/builders/venice.svg",
    networks: ["Arbitrum", "Base"],
    rewardType: "Pro Account",
    minDeposit: 0.001,
    totalStaked: 78492,
    stakingCount: 86,
    lockPeriod: "30 days",
  },
  {
    id: "2",
    name: "Morlord MOR Staking",
    image: "/builders/morlord.svg",
    networks: ["Base"],
    rewardType: "To Be Announced",
    minDeposit: 0,
    totalStaked: 44269,
    stakingCount: 6,
    lockPeriod: "7 days",
  },
  {
    id: "3",
    name: "coincap",
    image: "/builders/coincap.svg",
    networks: ["Arbitrum"],
    rewardType: "API Access",
    minDeposit: 0.001,
    totalStaked: 23936,
    stakingCount: 56,
    lockPeriod: "7 days",
  },
  {
    id: "4",
    name: "Morlord MOR Staking",
    image: "/builders/morlord.svg",
    networks: ["Base"],
    rewardType: "To Be Announced",
    minDeposit: 0.001,
    totalStaked: 20765,
    stakingCount: 24,
    lockPeriod: "30 days",
  },
  {
    id: "5",
    name: "MySuperAgent",
    image: "/builders/superagent.svg",
    networks: ["Arbitrum", "Base"],
    rewardType: "To Be Announced",
    minDeposit: 0.001,
    totalStaked: 12109,
    stakingCount: 3,
    lockPeriod: "30 days",
  },
  {
    id: "6",
    name: "MOR Builders",
    image: "/builders/builders.svg",
    networks: ["Arbitrum"],
    rewardType: "To Be Announced",
    minDeposit: 0.001,
    totalStaked: 11615,
    stakingCount: 19,
    lockPeriod: "30 days",
  },
  {
    id: "7",
    name: "Morpheus Asia",
    image: "/builders/asia.svg",
    networks: ["Base"],
    rewardType: "To Be Announced",
    minDeposit: 0.001,
    totalStaked: 3004,
    stakingCount: 9,
    lockPeriod: "30 days",
  },
  {
    id: "8",
    name: "Nounspace",
    image: "/builders/nounspace.svg",
    networks: ["Arbitrum", "Base"],
    rewardType: "Special OGs NFT",
    minDeposit: 0.001,
    totalStaked: 2582,
    stakingCount: 53,
    lockPeriod: "30 days",
  },
  {
    id: "9",
    name: "Wire Network",
    image: "/builders/wire.svg",
    networks: ["Base"],
    rewardType: "To Be Announced",
    minDeposit: 0.001,
    totalStaked: 2505,
    stakingCount: 20,
    lockPeriod: "30 days",
  },
  {
    id: "10",
    name: "DeFi Analytics",
    image: "/builders/venice.svg",
    networks: ["Arbitrum", "Base"],
    rewardType: "Premium Dashboard",
    minDeposit: 0.005,
    totalStaked: 35750,
    stakingCount: 42,
    lockPeriod: "14 days",
  },
  {
    id: "11",
    name: "AI Trading Bot",
    image: "/builders/builders.svg",
    networks: ["Base"],
    rewardType: "Bot Access",
    minDeposit: 0.002,
    totalStaked: 15890,
    stakingCount: 31,
    lockPeriod: "90 days",
  },
  {
    id: "12",
    name: "NFT Marketplace",
    image: "/builders/nounspace.svg",
    networks: ["Arbitrum"],
    rewardType: "Trading Fee Discount",
    minDeposit: 0.001,
    totalStaked: 8975,
    stakingCount: 67,
    lockPeriod: "60 days",
  },
  {
    id: "13",
    name: "GameFi Portal",
    image: "/builders/coincap.svg",
    networks: ["Base", "Arbitrum"],
    rewardType: "Game Credits",
    minDeposit: 0.003,
    totalStaked: 6420,
    stakingCount: 28,
    lockPeriod: "45 days",
  },
  {
    id: "14",
    name: "Yield Optimizer",
    image: "/builders/superagent.svg",
    networks: ["Arbitrum"],
    rewardType: "Strategy Access",
    minDeposit: 0.002,
    totalStaked: 4850,
    stakingCount: 15,
    lockPeriod: "30 days",
  },
  {
    id: "15",
    name: "Cross-Chain Bridge",
    image: "/builders/wire.svg",
    networks: ["Base", "Arbitrum"],
    rewardType: "Bridge Fee Discount",
    minDeposit: 0.004,
    totalStaked: 3275,
    stakingCount: 12,
    lockPeriod: "21 days",
  }
]; 